# Generated by Django 4.2.16 on 2024-11-21 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GameRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(db_column='Payment_date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(db_column='Rental_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.rental'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.user'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='game',
            field=models.ForeignKey(db_column='Game_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.game'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_date',
            field=models.DateTimeField(db_column='Rent_date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(db_column='Created_at', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(db_column='Game_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='GameRental.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_column='Date_joined', default=django.utils.timezone.now),
        ),
    ]
